name: Build and Publish Frontend App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions: 
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with: 
        node-version : '20'

    - name: Install dependencies
      run: npm install
      working-directory: ./frontend-app

    - name: Run unit tests
      run: npm test -- --watchAll=false --verbose
      working-directory: ./frontend-app


    - name: Run installation tests
      run: CI=false npm run build
      working-directory: ./frontend-app


      
  build-and-push:
    name: Build and Push Docker Image Frontend app
    needs : test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # - name: Run Trivy vulnerability scanner
    #   uses: aquasecurity/trivy-action@master
    #   with:
    #     scan-type: 'fs'
    #     scan-ref: '.'
    #     format: 'table'
    #     exit-code: '1'
    #     severity: 'CRITICAL,HIGH'

          # 1. Configurar credenciales de AWS
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Extract version
      id: vars
      run: echo "VERSION=1.0.${{ github.run_number }}" >> $GITHUB_ENV

     # 3. Construir y subir la imagen
    - name: Build, tag, and push image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: mi-app-repo-front
        #IMAGE_TAG: latest
      run: |
        docker build -t $ECR_REPOSITORY:${{ env.VERSION }} .
        docker tag $ECR_REPOSITORY:${{ env.VERSION }} $ECR_REGISTRY/$ECR_REPOSITORY:${{ env.VERSION }}
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ env.VERSION }}

    - name: Print Image URI
      run: echo "IMAGE URI:${{ steps.login-ecr.outputs.registry }}/mi-app-repo:${{ env.VERSION }}"    
  
      # ---------------- DEPLOY ----------------
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        debug: true

        script: |
          VERSION="${{ env.VERSION }}"
          ECR_REGISTRY="${{ steps.login-ecr.outputs.registry }}"
          ECR_REPO="mi-app-repo-front"

          echo "Deploying version $VERSION"

          if [ -z "$VERSION" ] || [ -z "$ECR_REGISTRY" ]; then
            echo "ERROR: VERSION o ECR_REGISTRY vac√≠o"
            exit 1
          fi

          echo "Logging into ECR..."
          aws ecr get-login-password --region us-east-1 | docker login \
            --username AWS --password-stdin "$ECR_REGISTRY"

          echo "Stopping old container..."
          docker stop mi-app-repo-front || true
          docker rm mi-app-repo-front || true

          echo "Cleaning old images..."
          docker images --format "{{.Repository}}:{{.Tag}}" \
            | grep "^$ECR_REGISTRY" \
            | xargs -r docker rmi || true

          echo "Pulling new image..."
          docker pull "$ECR_REGISTRY/$ECR_REPO:$VERSION"

          echo "Starting container..."
          docker run -d --name mi-app-repo-front -p 80:80 "$ECR_REGISTRY/$ECR_REPO:$VERSION"

          echo "Deployment complete."

